--| BANCO TRABALHO - CREATE DAS TABELAS

CREATE TABLE ADMINISTRADOR(
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    LOGIN CHAR(20) NOT NULL,
    SENHA INT NOT NULL
);

CREATE TABLE CATEGORIA(
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(60) NOT NULL
);

CREATE TABLE CLIENTE(
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(30) NOT NULL,
    --SOBRENOME VARCHAR(40) NOT NULL,
    --SEXO CHAR(1) NOT NULL,
    --DATANASCIMENTO DATE NOT NULL,
    CPF CHAR(11),
    ESTADO CHAR(2) NOT NULL,
    CIDADE VARCHAR(40) NOT NULL,
    BAIRRO VARCHAR(40) NOT NULL,
    CEP CHAR(8) NOT NULL,
    ENDERECO VARCHAR(80) NOT NULL,
    REFERENCIA VARCHAR(60) NOT NULL,
    IDENTIDADE VARCHAR(15) NOT NULL,
    TELFIXO CHAR(10) NOT NULL,
    CELULAR CHAR(11) NOT NULL,
    NUMCCREDITO char(16) NOT NULL,
    BANDCCREDITO VARCHAR(20) NOT NULL
);

CREATE TABLE PRODUTO(
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IDCATEGORIA INT UNSIGNED,
    NOME VARCHAR(40) NOT NULL,
    DESCRICAO VARCHAR(60) NOT NULL,
    VALOR FLOAT (11,2) NOT NULL,
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (IDCATEGORIA)
    REFERENCES CATEGORIA(ID)
);

CREATE TABLE COMPRAS(
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    IDCLIENTE INT UNSIGNED,
    IDPRODUTO INT UNSIGNED,
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(ID)
);


INSERT INTO PRODUTO (IDCATEG,NOME,DESCRICAO,VALOR) VALUES(1,'Televisao','LCD 42',100.00)

select * from produto

SELECT idcateg FROM produto

select * from categoria

select * from cliente

    
    ALTER TABLE CLIENTE MODIFY CPF CHAR(11) NOT NULL
    ALTER TABLE CLIENTE MODIFY CEP CHAR(8) NOT NULL
    ALTER TABLE CLIENTE MODIFY REFERENCIA VARCHAR(60)
    ALTER TABLE CLIENTE MODIFY IDENTIDADE VARCHAR(15) NOT NULL
    ALTER TABLE CLIENTE MODIFY TELFIXO CHAR(10) NOT NULL
    ALTER TABLE CLIENTE MODIFY CELULAR CHAR(11) NOT NULL
    ALTER TABLE CLIENTE MODIFY NUMCCREDITO CHAR(16) NOT NULL

SELECT produto.nome,categoria.descricao, produto.valor FROM COMPRAS, CLIENTE, PRODUTO, CATEGORIA WHERE CATEGORIA.id = produto.idcateg and compras.idcliente = cliente.id and compras.idproduto = produto.id